### PR TITLE
I am gonna mess this up

### PR DESCRIPTION
**Pull request by PulsarBane**
* Added a division function to the calculator.
* Added my own question to the trivia dictionary.

### CODE REVIEW

**Review by Obinnajude — CHANGES_REQUESTED** [review]
Hello PulsarBane, saw your pull request. Great to have you onboard. There is just a some little changes. On the quiz.py, please add comma after the question before yours. That separates the question.

For the Cal.py, you don't have to request input, that had been done. Just implement your code under the function provided, utilizing the inputs.

**Comment by PulsarBane** [comment]
Thanks for the opportunity! I will make the necessary changes as requested.

**Comment by PulsarBane** [comment]
Done! I made all the changes and noticed where I overlooked some of your instructions.

**Review by Obinnajude — APPROVED** [review]
Thanks a lot for your contribution. Your input has been merged. Great job

**Pull request merged**
